### ISSUE TITLE
Top left menu option text is affected by skybox color

### ISSUE THREAD

**Issue by Juuldamen** [open-osrs/runelite#2092]
**Describe the bug**
When using the GPU plugin and skyboxes together the menu option text in the top left of the client is also affected by it when the skybox is in the background.

**To Reproduce**
1. Turn on GPU plugin (might have to set fog depth higher than 0 if the issue does not show up)
2. Turn on Skybox plugin
3. Hover over a menu option with the skybox in the background

**Expected behavior**
The menu option text is not affected by the skybox color.

**Screenshots**
RuneLite
![RuneLite_2019-12-01_16-18-21](https://user-images.githubusercontent.com/31408341/69916236-ec28dd00-1458-11ea-9bca-b0ce003245e3.png)

OpenOSRS
![java_2019-12-01_16-18-49](https://user-images.githubusercontent.com/31408341/69916237-edf2a080-1458-11ea-9fbd-bb4ab930859c.png)

**Environment (please complete the following information):**
 - OS: Windows 10

**Comment by xKylee** [comment]
Does this occur on runelite also?
Because we haven’t touched this plugin

**Comment by Juuldamen** [comment]
> Does this occur on runelite also?
> Because we haven’t touched this plugin

It does not, the top image is from RuneLite with the same settings for GPU/Skybox plugin

**Comment by zeruth** [comment]
This is a problem with our alpha raw injector. Not sure if/when it will be fixed but its rather low priority.

**Comment by 40Cakes** [comment]
![image](https://user-images.githubusercontent.com/16377135/70386148-1135c680-19ea-11ea-8346-904663e71e3d.png)
Can confirm, I have the same issue with the same settings.

**Comment by zeruth** [comment]
This has been a known issue ever since Skitzo made the transition to our own injector. TBH it probably won't be fixed. So please stop discussion about this unless you are actively working on a fix.

**Comment by Lucwousin** [comment]
Fixed in f39c368bc69a4595af5d51d7a06a6ff11c152e
(https://github.com/open-osrs/openosrs-injector/commit/d49f9c080d00792f28b35ce6f0cec0eaf505ec75)

**Comment by Juuldamen** [comment]
The issue is still there for me on `2.1.19-SNAPSHOT` with version 1.0.3.0 of the injector-plugin
![java_2020-01-10_14-42-35](https://user-images.githubusercontent.com/31408341/72157294-dd1e3e80-33b7-11ea-9c3e-ed5426d29762.png)

![image](https://user-images.githubusercontent.com/31408341/72157459-4c942e00-33b8-11ea-8226-a8367b88c1d1.png)

GPU plugin settings, it does not seem to matter much if the skybox plugin is on or off
![image](https://user-images.githubusercontent.com/31408341/72157384-135bbe00-33b8-11ea-95e3-ccdf90e33935.png)

**Comment by xKylee** [comment]
@Juuldamen if youuse the latest launcher, and use nightly, does this still occur?

**Comment by Juuldamen** [comment]
Build using the latest upstream commit with version `2.1.21-SNAPSHOT`

**Comment by Owain94** [comment]
@Juuldamen you use your own project with a different build architecture than OpenOSRS has right? Did you update the injector? It should've been fixed with this commit https://github.com/open-osrs/openosrs-injector/commit/d49f9c080d00792f28b35ce6f0cec0eaf505ec75

**Comment by 40Cakes** [comment]
I just launched nightly & can confirm the menu is still transparent.

![image](https://user-images.githubusercontent.com/16377135/72190844-ac401700-3454-11ea-99c4-b1ca8734700d.png)
![image](https://user-images.githubusercontent.com/16377135/72190874-c5e15e80-3454-11ea-94c8-c2b169788406.png)

**Comment by Juuldamen** [comment]
@Owain94 This is using OpenOSRS but it also happens on SanLite yeah (same injector)

**Comment by xKylee** [comment]
@Juuldamen can you join the discord to discuss buddy?

**Comment by Owain94** [comment]
Fixed for real this time
