### ISSUE TITLE
Screenshot: Screenshot on death does not place death screenshots in its own folder anymore

### ISSUE THREAD

**Issue by GrimWrath** [open-osrs/runelite#2347]
When using the screenshot on death feature, the death screenshots are now stuffed in the same folder as level up and loot screenshots, causing a lot of clutter. Before the last update, they were in their own dedicated 'death' subfolder within the screenshots folder.

**Comment by xKylee** [comment]
@GrimWrath this should be resolved, can you confirm please?

**Comment by GrimWrath** [comment]
The issue is not resolved. I will try re-toggling the plugin and report what happens.

**Comment by GrimWrath** [comment]
Retoggling plugin and creating a new 'Deaths' folder fixes this bug. Thanks for the 'Boss Kills' folder as well. Really helps organize.
